import { NextResponse } from "next/server";
import {
  Product,
  ProductCategory,
  ProductUnit,
  MarketResponse,
  FarmingMethod,
  Farm,
  UserType,
} from "@/types";

// --- Config ---
export const dynamic = "force-dynamic"; // don't cache this route during dev

// Sample farm data
const sampleFarm: Farm = {
  id: "farm_1",
  name: "Green Valley Farm",
  description: "A family-owned organic farm",
  address: {
    street: "123 Farm Road",
    city: "Charlotte Amalie",
    state: "VI",
    zipCode: "00802",
    country: "US",
  },
  rating: 4.8,
  reviewCount: 150,
  images: [
    "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=300&h=200&fit=crop",
  ],
  coverImage:
    "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=300&h=200&fit=crop",
  certified: true,
  certifications: [],
  specialties: ["Organic Vegetables"],
  ownerId: "owner_1",
  owner: {
    id: "owner_1",
    email: "owner@greenvalley.vi",
    username: "greenvalley",
    firstName: "John",
    lastName: "Smith",
    userType: UserType.FARMER,
    isVerified: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  contact: {
    phone: "(340) 555-0123",
    email: "info@greenvalleyfarm.vi",
  },
  products: [],
  deliveryOptions: [],
  paymentMethods: [],
  isActive: true,
  createdAt: "2024-01-01T00:00:00Z",
  updatedAt: "2024-01-01T00:00:00Z",
};

// --- Handler ---
export async function GET() {
  // In a real implementation, you would parse query parameters and filter data
  // For now, return sample data

  const sampleProducts: Product[] = [
    {
      id: "1",
      cartId: "2",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Organic Tomatoes",
      description:
        "Fresh, vine-ripened organic tomatoes grown in rich Virgin Islands soil.",
      price: 4.5,
      color: "blue",
      quantity: 2,
      unit: ProductUnit.POUND,
      quantityAvailable: 50,
      images: [
        "/mix-of-red-sweet-tomatoes-2024-10-11-22-22-06-utc.jpg",
      ],
      primaryImage:
        "/mix-of-red-sweet-tomatoes-2024-10-11-22-22-06-utc.jpg",
      category: ProductCategory.VEGETABLES,
      tags: ["organic", "fresh"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "2",
      cartId: "23",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Fresh Basil",
      description: "Aromatic basil leaves perfect for cooking.",
      price: 3.25,
      color: "blue",
      quantity: 2,
      unit: ProductUnit.BUNCH,
      quantityAvailable: 15,
      images: [
        "/bunch-of-fresh-organic-basil-in-cutting-board-on-r-2025-02-11-14-01-29-utc.jpg",
      ],
      primaryImage:
        "/bunch-of-fresh-organic-basil-in-cutting-board-on-r-2025-02-11-14-01-29-utc.jpg",
      category: ProductCategory.HERBS,
      tags: ["fresh", "aromatic"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "3",
      cartId: "24",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Fresh Bananas",
      description: "Sweet, ripe bananas grown in the tropical Virgin Islands climate.",
      price: 2.5,
      color: "yellow",
      quantity: 1,
      unit: ProductUnit.POUND,
      quantityAvailable: 60,
      images: [
        "/bunch-of-bananas-on-gray-background-shopping-for-2025-01-10-04-57-31-utc.jpg",
      ],
      primaryImage:
        "/bunch-of-bananas-on-gray-background-shopping-for-2025-01-10-04-57-31-utc.jpg",
      category: ProductCategory.FRUITS,
      tags: ["sweet", "tropical", "nutritious"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "4",
      cartId: "25",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Fresh Pineapple",
      description: "Sweet, juicy pineapple grown in the tropical Virgin Islands sun.",
      price: 4.75,
      color: "yellow",
      quantity: 1,
      unit: ProductUnit.EACH,
      quantityAvailable: 18,
      images: [
        "/nominated-2024-11-07-13-31-21-utc.jpg",
      ],
      primaryImage:
        "/nominated-2024-11-07-13-31-21-utc.jpg",
      category: ProductCategory.FRUITS,
      tags: ["sweet", "tropical", "juicy"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "5",
      cartId: "26",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Fresh Thyme",
      description: "Aromatic Caribbean thyme, essential for seasoning local dishes.",
      price: 2.75,
      color: "green",
      quantity: 1,
      unit: ProductUnit.BUNCH,
      quantityAvailable: 30,
      images: [
        "/fresh-thyme-sprigs-bunch-isolated-on-white-backgro-2024-12-10-03-18-19-utc.JPG",
      ],
      primaryImage:
        "/fresh-thyme-sprigs-bunch-isolated-on-white-backgro-2024-12-10-03-18-19-utc.JPG",
      category: ProductCategory.HERBS,
      tags: ["aromatic", "seasoning", "caribbean"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "6",
      cartId: "27",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Farm Fresh Eggs",
      description: "Free-range eggs from local Virgin Islands chickens.",
      price: 4.25,
      color: "brown",
      quantity: 1,
      unit: ProductUnit.DOZEN,
      quantityAvailable: 40,
      images: [
        "/white-and-brown-eggs-on-linen-cloth-2025-04-04-11-25-56-utc.jpg",
      ],
      primaryImage:
        "/white-and-brown-eggs-on-linen-cloth-2025-04-04-11-25-56-utc.jpg",
      category: ProductCategory.EGGS,
      tags: ["free-range", "fresh", "local"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "7",
      cartId: "28",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Goat Milk",
      description: "Fresh, creamy goat milk from local Virgin Islands goats.",
      price: 7.0,
      color: "white",
      quantity: 1,
      unit: ProductUnit.QUART,
      quantityAvailable: 15,
      images: [
        "/glass-of-milk-2024-09-18-20-02-35-utc.jpg",
      ],
      primaryImage:
        "/glass-of-milk-2024-09-18-20-02-35-utc.jpg",
      category: ProductCategory.DAIRY,
      tags: ["fresh", "creamy", "goat"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "8",
      cartId: "29",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Fresh Passion Fruit Juice",
      description: "Freshly squeezed passion fruit juice with tropical island flavor.",
      price: 8.5,
      color: "orange",
      quantity: 1,
      unit: ProductUnit.QUART,
      quantityAvailable: 18,
      images: [
        "/glass-of-iced-passion-fruit-soda-with-lemon-and-pa-2025-03-26-13-57-16-utc.jpg",
      ],
      primaryImage:
        "/glass-of-iced-passion-fruit-soda-with-lemon-and-pa-2025-03-26-13-57-16-utc.jpg",
      category: ProductCategory.BEVERAGES,
      tags: ["fresh", "tropical", "passion fruit"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "9",
      cartId: "30",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Coconut Water",
      description: "Fresh coconut water straight from young green coconuts.",
      price: 4.0,
      color: "clear",
      quantity: 1,
      unit: ProductUnit.PINT,
      quantityAvailable: 35,
      images: [
        "/coconut-water-and-coconuts-on-a-bright-pastel-back-2024-12-05-17-32-33-utc.jpg",
      ],
      primaryImage:
        "/coconut-water-and-coconuts-on-a-bright-pastel-back-2024-12-05-17-32-33-utc.jpg",
      category: ProductCategory.BEVERAGES,
      tags: ["fresh", "coconut", "natural"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "10",
      cartId: "31",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Plantains",
      description: "Sweet ripe plantains perfect for frying or baking.",
      price: 2.25,
      color: "yellow",
      quantity: 1,
      unit: ProductUnit.POUND,
      quantityAvailable: 45,
      images: [
        "/whole-yellow-plantains-2025-03-23-20-47-57-utc.jpg",
      ],
      primaryImage:
        "/whole-yellow-plantains-2025-03-23-20-47-57-utc.jpg",
      category: ProductCategory.FRUITS,
      tags: ["sweet", "caribbean", "versatile"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "11",
      cartId: "32",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Tamarind",
      description: "Fresh tamarind pods with sweet and tangy pulp.",
      price: 5.75,
      color: "brown",
      quantity: 1,
      unit: ProductUnit.POUND,
      quantityAvailable: 20,
      images: [
        "/organic-raw-brown-tamarind-2025-01-16-16-17-01-utc.jpg",
      ],
      primaryImage:
        "/organic-raw-brown-tamarind-2025-01-16-16-17-01-utc.jpg",
      category: ProductCategory.FRUITS,
      tags: ["tangy", "tropical", "flavorful"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "12",
      cartId: "33",
      farmId: "farm_1",
      farm: sampleFarm,
      name: "Fresh Mint",
      description: "Aromatic fresh mint leaves perfect for teas, cocktails, and cooking.",
      price: 3.0,
      color: "green",
      quantity: 1,
      unit: ProductUnit.BUNCH,
      quantityAvailable: 25,
      images: [
        "/sprig-of-mint-on-wooden-board-2024-11-03-03-23-34-utc.jpg",
      ],
      primaryImage:
        "/sprig-of-mint-on-wooden-board-2024-11-03-03-23-34-utc.jpg",
      category: ProductCategory.HERBS,
      tags: ["aromatic", "refreshing", "versatile"],
      inSeason: true,
      farmingMethod: FarmingMethod.ORGANIC,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
  ];

  const body: MarketResponse = {
    products: sampleProducts,
    farms: [sampleFarm],
    page: 1,
    pageSize: 12,
    total: sampleProducts.length,
    totalPages: 1,
    appliedFilters: {},
  };

  await new Promise((r) => setTimeout(r, 500)); // simulate load

  return NextResponse.json(body, {
    headers: { "Cache-Control": "no-store" },
  });
}
